### ISSUE TITLE
epic免费游戏 被动提醒和主动触发都显示不了图片

### ISSUE THREAD

**Issue by william-wwh** [HibiKier/zhenxun_bot#504] opened 2022-05-21 12:20 UTC
![FYWH114FPP869AW 5HGLR2I](https://user-images.githubusercontent.com/60587573/169651193-49dd792f-f003-433a-93d7-0f5d594ee63e.png)

![{EUDEDH8N7GW{%UK50HF2(V](https://user-images.githubusercontent.com/60587573/169651198-a0b9c00b-38e6-4ed3-965a-84230ec7d88f.png)
bot.py

![OC%}2$9~~{`T@GPS}((6OLJ](https://user-images.githubusercontent.com/60587573/169651201-2ca9ba4c-013e-4cb8-b7c1-46927e540be6.png)
go-cqhttp

**Comment by MingxuanGame** [comment] 2022-05-21 12:32
Duplicate of #483

**Comment by HibiKier** [comment] 2022-05-22 07:26
92e60ba141313f5b28f89afdfe813b29f13468c1

**Closed by HibiKier** 2022-05-22 07:26 UTC
