### ISSUE TITLE
麻烦问下，bot只能回复文本，图片和声音都不行，提示以下报错，但是docker容器中确实可以找到

### ISSUE THREAD

**Issue by qiuyang163** [HibiKier/zhenxun_bot#277] opened 2022-05-18 13:57 UTC
![image](https://user-images.githubusercontent.com/8520472/169058266-c8aa412c-6605-4759-bd0d-501cb2bd1043.png)
![image](https://user-images.githubusercontent.com/8520472/169058764-7bb31906-90ed-4138-90d9-1f0f4987cf8d.png)

**Comment by MingxuanGame** [comment] 2022-05-18 14:12
duplicate of #275 

see #165

**Comment by qiuyang163** [comment] 2022-05-18 14:17
@MingxuanGame tks for your time，after add soft link，the question has been solved

**Comment by MingxuanGame** [comment] 2022-05-18 14:24
> @MingxuanGame tks for your time，after add soft link，the question has been solved

please close this  issue

**Closed** 2022-05-18 14:28 UTC
